coverage:
  status:
    project:
      default:
        # Fail the status if coverage drops by >= 3%
        threshold: 3
    patch:
      default:
        threshold: 
Scatter +scatter +scatter +scatter 4+1000= bigwin 1000